### ISSUE TITLE
FaultResponseTakble does stop propagating any exceptions emitted by monitors

### ISSUE THREAD

**Issue by D-Alex** [rock-core/tools-roby#44]
It seems that either I completely misuse the FaultResponseTable or there are several bugs:
- see https://github.com/D-Alex/tools-roby/commit/018ee6e94a9cb6ffb16b86b4123c9776f57c476b
- DataMonitoringError is handled by the on_fault block but it still gets propagated to the Roby::Plan which handles it. Therefore, the plan is passed to https://github.com/rock-core/tools-roby/blob/master/lib/roby/interface/interface.rb#L489 instead of the task resulting in a method_missing error #fullfils? https://github.com/rock-core/tools-roby/blob/master/lib/roby/interface/interface.rb#L311

Some help would be welcome.

**Comment by D-Alex** [comment]
Ok, this is obviously correct. The error is propagated to the plan and then handled by the response table. But still, the error is propagated to the roby shell interface with the plan instead of the real task involved in the exception resulting in the method_missing error https://github.com/rock-core/tools-roby/blob/master/lib/roby/execution_engine.rb#L1183.

The question is how to get the task at this point. Using exception.task results in a new error on the remote side. Are you actually using FaultResponseTables?

**Comment by doudou** [comment]
> Are you actually using FaultResponseTables?

Not for the 1.5 year or so. We're going to pretty soon though. As you identified it, the bug is in the reporting, which assumes that exceptions are always handled by tasks -- forgetting about plans and other possible objects.

**Comment by D-Alex** [comment]
I have a working fix on my machine which replaces the plan by the exception.task if the object passed to the following hook is not a Roby::Task. 
https://github.com/rock-core/tools-roby/blob/master/lib/roby/interface/interface.rb#L487

Is there a better way? Ideally the execution engine would get the correct object form here.
https://github.com/rock-core/tools-roby/blob/master/lib/roby/execution_engine.rb#L1236 instead of just true or false and use it instead of the plan object.

**Comment by doudou** [comment]
replacing plan by exception.task is giving the wrong information (it's saying whoever is listening that the task that handled the exception is exception.task ... while it actually is the plan)

It is normal to have the plan as an exception handler, what is buggy is the rest of the code that is not handling it properly.

**Comment by D-Alex** [comment]
The problem is that the roby shell needs the exact job id which is not part of the plan, is it? (the plan can have several jobs running)

**Comment by doudou** [comment]
> The problem is that the roby shell needs the exact job id which is not part of the plan, is it? (the plan can have several jobs running)

Actually, it needs the list of jobs that are involved in the notification. The way it is done right now is stupid (it just happens that for fatal exceptions they match). The right way would be to iterate over `ExecutionException#trace`.

**Comment by doudou** [comment]
For information, the exception handling has been totally rewritten on Roby3, and explicitly recognizes the plan as an exception handler. I'll check whether this bug still exists.

**Comment by doudou** [comment]
> I'll check whether this bug still exists.

Doesn't according to my testing ... Closing now.
