### ISSUE TITLE
distributed: Roby::Task is not correctly marshalled 

### ISSUE THREAD

**Issue by D-Alex** [rock-core/tools-roby#45]
# action_script is generating a Roby::Task behind the scene
- (see discussion https://github.com/rock-core/tools-roby/commit/495fb8b40dfe7f5f39357ddc540834fca07ecd50#commitcomment-14872252). 

This task sets the failed event to be controllable. Now if the action_script emits the failed_event the roby shell gets the correct event but prints the following warning and does not display the state change. 
- https://github.com/rock-core/tools-roby/blob/master/lib/roby/distributed/protocol.rb#L594

The reason is that the event is controllable but the task.event(symbol) is not. I guess there is an error in how the task gets marshaled and reconstructed.

As workaround one can simply set the return value of the action script: 

```
describe(...).returns(Roby::Task.new_submodule)
action_script(...)
```

Also the warning is really difficult to understand. I would change it to something like. 
- Internal error ... emitted event does not fit to task model ... Report this error ...

**Comment by D-Alex** [comment]
Ehhhh. The remote side just looks for a constant with the same name which of course is not defined for any auto generated class and also not for any user defined class (roby shell does not support the -r option). Because of that it just uses a Roby::Task but forgets to set the correct controllable flags.

**Comment by doudou** [comment]
> Because of that it just uses a Roby::Task but forgets to set the correct controllable flags.

It (does|should) reconstruct an anonymous submodel of Roby::Task that has the "right" parameters. You're hitting a corner case, as it works for most of the cases (e.g. OroGen tasks in syskit ...)

**Comment by D-Alex** [comment]
Why is this a corner case? All actions scripts are effected if they emit failed. This happens for example if one of their tasks fails.

    action_script(...)
        ...
        move.depends_on fence  # fence emits failed if the robot hits the fence
        ....
    end

**Comment by doudou** [comment]
> All actions scripts are effected if they emit failed

You mean: it happens to any action script ? I did not understand that !

**Comment by D-Alex** [comment]
Yes, any action_script which emits failed instead of success.

**Comment by doudou** [comment]
The DRoby marshalling layer has been completely rewritten in roby3, and the new method does not have the same problem. Closing this.
