### ISSUE TITLE
I have issue in my rails server..

### ISSUE THREAD

**Issue by Faari7** [rock-core/tools-roby#52]
it was worked fine before i installed sqlite3 by this method 
Install the Ruby Devkit for your setup (DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe for me since I use a x64 machine)
Download and extract the autoconf package from Sqlite.org
Run msys.bat (it is inside the ruby devkit root folder)
cd into the path where you downloaded the sqlite source (for example: "cd /c/dev/sqlite3" for path "c:\dev\sqlite3" if you are new to MSYS/MINGW32)
Run "./configure"
Run "make"
Run "make install"
Get the sqlite3 gem again, this time specifying the platform and the path to the newly compiled binaries:

Now when i run rails server it shows me this instead of running the server
![untitled](https://cloud.githubusercontent.com/assets/20708623/20845385/ab07408a-b8e6-11e6-857a-ad113760714a.png)

**Comment by doudou** [comment]
Either you're really completely clueless, or this is an attempt at drive-by-download.

Assuming the former, in case you've not **even** looked, roby is a robotics framework. Has nothing to do with Rails (except from being written in Ruby, the programming language)
