### ISSUE TITLE
interface: fails to detect a new job if the plan pattern was added in a transaction

### ISSUE THREAD

**Issue by alcantara09** [rock-core/tools-roby#88]
We're adding a new job from within an action (i.e. within a transaction) and the IDE does not see it.

Getting through a debugging session, the problem seem to be that the interface never generates the MONITORED event at https://github.com/rock-core/tools-roby/blob/roby3/lib/roby/interface/interface.rb#L367. It might be related to https://github.com/rock-core/tools-roby/commit/039d8bc2260c20afa53ec16fd149c22c2b8ad7bc.

**Comment by doudou** [comment]
Fixed on master
